"""
Business Intelligence Pipeline
================================

Runs the complete BI analytics pipeline in sequence.

Pipeline:
1. Raw data validation
2. KPI inspection
3. Driver feature engineering
4. Materiality detection
5. Analytic agent
6. Historical validation
7. Hypothesis ranking
8. Evidence building
9. Narrative generation
10. Action recommendation

Each stage reads the output generated by the previous stage.
"""

import subprocess
import sys
from pathlib import Path
from datetime import datetime


# ============================================================
# PATH CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parents[2]
SCRIPT_DIR = Path(__file__).resolve().parent


# ============================================================
# PIPELINE STAGES
# ============================================================

STAGES = [
    ("Raw Data Validation", "validation_raw_data.py"),
    ("KPI Inspection", "inspect_kpis.py"),
    ("Driver Feature Engineering", "driver_features.py"),
    ("Materiality Detection", "materiality_detector.py"),
    ("Analytic Agent", "analytic_agent.py"),
    ("Historical Validation", "Historical_validator.py"),
    ("Hypothesis Ranking", "Hypothesis_ranking.py"),
    ("Evidence Builder", "evidence_builder.py"),
    ("Narrative Generation", "narrative_generator.py"),
    ("Action Recommendation", "action_recommender.py"),
]


# ============================================================
# DISPLAY HELPERS
# ============================================================

def print_header():
    print()
    print("=" * 70)
    print("BUSINESS INTELLIGENCE PIPELINE")
    print("=" * 70)
    print(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print()


def print_stage_header(stage_number, total_stages, stage_name):
    print()
    print("-" * 70)
    print(f"STAGE {stage_number}/{total_stages}: {stage_name}")
    print("-" * 70)


# ============================================================
# RUN A SINGLE STAGE
# ============================================================

def run_stage(stage_number, total_stages, stage_name, script_name):

    print_stage_header(
        stage_number,
        total_stages,
        stage_name
    )

    script_path = SCRIPT_DIR / script_name

    if not script_path.exists():
        print(f"ERROR: Script not found:")
        print(f"       {script_path}")
        return False

    print(f"Running: {script_name}")
    print()

    try:

        result = subprocess.run(
            [sys.executable, str(script_path)],
            cwd=str(BASE_DIR),
            check=False
        )

        if result.returncode != 0:
            print()
            print(f"✗ {stage_name} FAILED")
            print(f"Return code: {result.returncode}")
            return False

        print()
        print(f"✓ {stage_name} COMPLETE")
        return True

    except Exception as e:

        print()
        print(f"✗ {stage_name} FAILED")
        print(f"Error: {e}")
        return False


# ============================================================
# MAIN PIPELINE
# ============================================================

def main():

    print_header()

    total_stages = len(STAGES)

    successful_stages = 0

    for i, (stage_name, script_name) in enumerate(STAGES, start=1):

        success = run_stage(
            i,
            total_stages,
            stage_name,
            script_name
        )

        if not success:

            print()
            print("=" * 70)
            print("PIPELINE FAILED")
            print("=" * 70)
            print(f"Failed stage : {stage_name}")
            print(f"Script       : {script_name}")
            print()
            print("Pipeline execution stopped.")
            print("=" * 70)

            sys.exit(1)

        successful_stages += 1

    print()
    print("=" * 70)
    print("BUSINESS INTELLIGENCE PIPELINE COMPLETE")
    print("=" * 70)

    print(
        f"Stages completed : "
        f"{successful_stages}/{total_stages}"
    )

    print(
        f"Finished at      : "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    print()
    print("Final outputs are available in:")
    print(f"  {BASE_DIR / 'Data_processed'}")
    print()
    print("=" * 70)


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()